PROJECT_NAME=%{ $PRJ_NAME }%
PROJECT_VERSION=%{ $PKG_VER }%
PACKAGE_NAME=%{ $PKG_NAME }%
GCOV=%{ $CB_GCOV }%
BASEDIR=$(shell pwd)
PRJ_BINDIR=%{ $PRJ_BINDIR }%
% if (($CB_CPUS > 1)); then
CB_JOBS=-j%{ $CB_CPUS }%
% else
CB_JOBS=
% fi

all: build-project

build-project:
	@$(MAKE) $(CB_JOBS) -C build

% declare -a BIN_TARGETS
%
% for TARGET in ${PRJ_BINS[@]}; do
%     TARGET=bin_${TARGET}
%     BIN_TARGETS+=($TARGET)
%{ $TARGET }%:
	@$(MAKE) $(CB_JOBS) -C build %{ $TARGET }%

% done

binaries: %{ ${BIN_TARGETS[@]} }%

% declare -a LIB_TARGETS
%
% for TARGET in ${PRJ_LIBS[@]}; do
%     if [[ "${HLIB_TARGET_MAP[$TARGET]}" ]]; then
%         continue
%     fi
%
%     TARGET=lib_${TARGET}
%     LIB_TARGETS+=($TARGET)
%{ $TARGET }%:
	@$(MAKE) $(CB_JOBS) -C build %{ $TARGET }%

% done

libraries: %{ ${LIB_TARGETS[@]} }%

% declare -a PLUG_TARGETS
%
% for TARGET in ${PRJ_PLUGS[@]}; do
%     TARGET=plug_${TARGET}
%     PLUG_TARGETS+=($TARGET)
%{ $TARGET }%:
	@$(MAKE) $(CB_JOBS) -C build %{ $TARGET }%

% done

plugins: %{ ${PLUG_TARGETS[@]} }%

% declare -a TST_TARGETS
%
% for TARGET in ${PRJ_TSTS[@]}; do
%     TARGET=tst_${TARGET}
%     TST_TARGETS+=($TARGET)
%{ $TARGET }%:
	@$(MAKE) $(CB_JOBS) -C build %{ $TARGET }%

% done

tests: %{ ${TST_TARGETS[@]} }%

test: tests
	@cd build && env PRJ_BINDIR=$(PRJ_BINDIR) prove -r -m -e '' t

test-verbose: tests
	@cd build && env PRJ_BINDIR=$(PRJ_BINDIR) prove -v -r -m -e '' t

test-report: tests
	@mkdir -p build/quality-reports/tests
	@cd build && env PRJ_BINDIR=$(PRJ_BINDIR) prove \
	    -v -r -m -e '' \
	    -P HTML=outfile:quality-reports/tests/index.html,force_inline_css:1,force_inline_js:1 \
	    t || true

coverage-report:
	@rm -rf build/coverage
	@mkdir -p build/coverage
	@echo "building coverage data"

	@cd build && ( \
		gcovr \
			-e '/usr/include.*' \
			--html --html-details \
			-o coverage/index.html \
	    ; \
	    sed -i"" -r -e 's,>[^<]+/sources/,>,g' coverage/*.html \
	)

doc:
	@cd build/doc && doxygen 2> doxygen.log

% if (($CPKG_IS_DEB)); then
package: build-project
	@cd build && ( \
		rm -rf usr etc && \
		make DESTDIR=packaging install | grep -v '^-- ' && \
		cd packaging && dpkg-buildpackage -b -uc \
	)
% elif (($CPKG_IS_PKGSRC)); then
package:
	@rsync -aq build/packaging/ %{ $PKGSRC_DIR/$PKG_CAT/$PKG_NAME/ }%
	@cd %{ $PKGSRC_DIR/$PKG_CAT/$PKG_NAME/ }% && ( \
		sudo -s -- " \
		    bmake distclean && \
		    bmake fetch && \
		    bmake mdi && \
		    bmake && \
		    bmake stage-install CHECK_FILES=no && \
		    bmake print-PLIST > PLIST && \
		    bmake install-clean && \
		    bmake package \
		" \
	)
% fi

update-pkg: package
% if (($CPKG_IS_DEB)); then
	@sudo dpkg -i build/*.deb
% elif (($CPKG_IS_PKGSRC)); then
	@sudo -s -- " \
	    pkg_add \
	        -U \
	        %{ $PKGSRC_DIR/packages/All/${PKG_NAME}-${PKG_VER}.tgz }% \
	"
% fi

install:
	@cd build && (make DESTDIR=$(DESTDIR) install | grep -v '^-- ')

% if (($CPKG_IS_DEB)); then
upload:
	@cd DEBS && erepo-upload
% fi

clean:
	@rm -rf build
% if (($CPKG_IS_DEB)); then
	@rm -f DEBS/$(PACKAGE_NAME)*
% fi

distclean: clean
	@rm -rf .cbuild
