# $NetBSD$

PKGNAME=	%{ ${PKG_NAME} }%-%{ ${PKG_VER} }%
CATEGORIES=	%{ ${PKG_CAT} }%
% if (($PKG_FROM_GIT)); then
HOMEPAGE=	%{ ${PKG_GIT_URL} }%
GITCOMMIT=	%{ ${PKG_GIT_COMMIT} }%
MASTER_SITES=	%{ ${PKG_GIT_FETCH_URL} }%
%     if (($PKG_FROM_GITHUB)); then
DISTNAME=	${GITCOMMIT}.zip
DIST_SUBDIR=	%{ ${PKG_NAME} }%
%     elif (($PKG_FROM_GITLIST)); then
DISTNAME=	${GITCOMMIT}
DISTFILES=	${GITCOMMIT}.zip
EXTRACT_DIR=	${WRKSRC}
%     fi
% fi
EXTRACT_SUFX=	# none

MAINTAINER=	%{ ${PKG_AUTHOR_EMAIL} }%
COMMENT=	%{ ${PKG_SHORTDESC} }%
LICENSE=	mit
%
% declare -a BLINK3
%
% if ((${#PRJ_PKGS[@]})); then

%     for DEP in ${!PRJ_PKGS[@]}; do
%         DPATH=$(pkg_info -Q PKGPATH $DEP)
%         DNAME=$(basename $DPATH)
%         BLINK3+=("../../$DPATH/buildlink3.mk")
DEPENDS+=	%{ $DNAME }%>=0:../../%{ $DPATH }%
%     done
% fi

WRKSRC=		${WRKDIR}/%{ ${PKG_NAME} }%-${GITCOMMIT}
USE_LANGUAGES=	c c++
USE_CMAKE=	yes
USE_TOOLS+= gmake pkg-config
% CFGFILES=$(cp_find_rel $PKG_SOURCEDIR/etc)
% if [[ -n "$CFGFILES" ]]; then

EGDIR=		${PREFIX}/share/${PKGBASE}/etc/${PKGBASE}
%     for CFGFILE in $CFGFILES; do
CONF_FILES+=	${EGDIR}/%{ $CFGFILE }% \
		${PKG_SYSCONFDIR}/${PKGBASE}/%{ $CFGFILE }%
%     done

OWN_DIRS+=	${PKG_SYSCONFDIR}/${PKGBASE}
% CFGDIRS=$(cp_find_rel $PKG_SOURCEDIR/etc "d")
%     for CFGDIR in $CFGDIRS; do
OWN_DIRS+=	${PKG_SYSCONFDIR}/${PKGBASE}/%{ $CFGDIR }%
%     done
% fi

CBUILD=		cbuild

do-configure:
	@cd ${WRKSRC} && env ${MAKE_ENV} ${CBUILD} -C

% for BL3 in ${BLINK3[@]}; do
.include "%{ $BL3 }%"
% done
.include "../../mk/bsd.pkg.mk"
